trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js 18'

- script: |
    npm install
    npm install -g gulp
  displayName: 'Install npm packages'

- script: |
    gulp clean
    gulp bundle --ship
    gulp package-solution --ship
  displayName: 'Bundle and Package SPFx Solution'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'sharepoint/solution'
    artifactName: 'drop'
  displayName: 'Publish Package'
