trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CDN_PATH: $(CDN_PATH)  # Defined in Azure DevOps

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js 18'

- script: |
    npm install
  displayName: 'Install npm packages'

- script: |
    npm run clean
    npm run update-manifest --cdnpath $(CDN_PATH)
    npm run build
    npm run package
  displayName: 'Build and Package SPFx Solution'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'sharepoint/solution'
    artifactName: 'drop'
  displayName: 'Publish Package'
